# Generated by Django 6.0.2 on 2026-02-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
