# Generated by Django 6.0.2 on 2026-02-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_pin_address_pin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
