# Generated by Django 6.0.2 on 2026-02-20 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_pin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='default_id',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
