# Generated by Django 6.0.2 on 2026-02-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_pinimage'),
        ('world', '0004_alter_pin_address'),
        ('world', '0004_pin_default_id'),
    ]

    operations = [
    ]
